# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40410ab66a6f07fdc100c019e6bd7877aca47e784d4c064c32813474bbf7dc16390f9ad1793a101acc93cfa91f585d8eba92e52a48f2102c5e4cd16cb387c484

test:
  secret_key_base: 2ada200590c769d401f977d8f3c24fb9090fa3258eb87f9e2699f43c1c5280822303f7e7474f6925e2c33d1365c29801277d23aa09168bff60b20a671535cac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
